### PR TITLE
Gameplay expansion list

### PR DESCRIPTION
**Pull request by One-Voxie-Girl**

### CODE REVIEW

**Comment by One-Voxie-Girl** [comment]
testgimp

**Comment by Rathguard** [comment]
https://github.com/One-Voxie-Girl/CO3105_CW2/assets/124172785/5ed81306-ad6a-4779-b8a8-07f6e36b421f

**Comment by Rathguard** [comment]
https://github.com/One-Voxie-Girl/CO3105_CW2/assets/124172785/d29b65c1-4663-4028-bb32-81845cbf2b83

**Comment by One-Voxie-Girl** [comment]
https://github.com/One-Voxie-Girl/CO3105_CW2/assets/72501470/2f2e951b-27e4-43b0-aefd-3253ff732940

**Pull request merged**
