### PR TITLE
Gameplay expansion

### PR DESCRIPTION
**Pull request by One-Voxie-Girl**

### CODE REVIEW

**Comment by Rathguard** [comment]
F_ueWgnXwAAg0IL

**Comment by Rathguard** [comment]
[MA_dissertation_1.pdf](https://github.com/One-Voxie-Girl/CO3105_CW2/files/13622296/MA_dissertation_1.pdf)

**Comment by One-Voxie-Girl** [comment]
https://github.com/One-Voxie-Girl/CO3105_CW2/assets/72501470/e46bf341-6389-4b87-beca-b01a6e046805

**Comment by One-Voxie-Girl** [comment]
https://github.com/One-Voxie-Girl/CO3105_CW2/assets/72501470/5ac38d54-1413-4936-bf0e-68fb4cb0a921

**Pull request merged**
